/**
 * Storage root initialisation — ensures the on-disk layout required by the
 * Nearbytes meta-storage specification exists and is up to date.
 *
 * Spec reference: storage/meta-storage-v2.md §4.1
 *
 * On-disk layout maintained by this module:
 *
 *   <root>/
 *     Nearbytes.html          ← discovery marker, rewritten on every startup
 *     blocks/
 *       <sha256-hex>.bin      ← encrypted content blocks
 *     channels/
 *       <pubkey-hex>/         ← one directory per volume
 *         <event-hash>.bin    ← signed, encrypted events
 *
 * Node.js only: this module uses fs/promises and MUST NOT be imported in
 * browser bundles.  The package.json "browser" field or conditional exports
 * should map this module to a no-op shim when targeting browsers.
 */

import { mkdir, writeFile, rm, access, readdir, unlink, stat } from 'fs/promises';
import { join } from 'path';
import { constants } from 'fs';

/**
 * Builds the `Nearbytes.html` discovery marker for a storage root.
 *
 * This file serves two purposes:
 *   1. Discovery — helps users and tools recognise a Nearbytes root.
 *   2. Self-documentation — explains the on-disk layout to anyone who finds
 *      these files without prior knowledge of Nearbytes ("alien scenario").
 *
 * In a future version this file will also embed a minimal self-contained
 * reader application: supply your secret, read your files — no installation
 * required.
 *
 * The file is always overwritten on startup so it remains current with the
 * running application version.  It MUST NOT be treated as durable data.
 */
function buildNearbytesHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Nearbytes storage root</title>
  <style>
    body   { font-family: system-ui, sans-serif; max-width: 640px; margin: 3rem auto; padding: 0 1.5rem; line-height: 1.7; color: #111; }
    h1     { font-size: 1.4rem; font-weight: 700; letter-spacing: -0.02em; }
    h2     { font-size: 1rem; font-weight: 600; margin-top: 2.2rem; color: #333; }
    pre    { background: #f5f5f5; border-radius: 6px; padding: 0.9rem 1.1rem; font-size: 0.85em; overflow-x: auto; line-height: 1.5; }
    code   { font-family: ui-monospace, 'Cascadia Code', monospace; }
    .note  { border-left: 3px solid #ccc; padding-left: 0.9rem; color: #555; font-size: 0.93rem; }
    footer { margin-top: 3rem; font-size: 0.8rem; color: #888; }
  </style>
</head>
<body>

  <h1>Nearbytes storage root</h1>

  <p>
    This folder is a <strong>Nearbytes storage root</strong> — an encrypted,
    content-addressed event log and block store.
  </p>
  <p>
    All data stored here is end-to-end encrypted.
    No plaintext content, filenames, or metadata is stored on disk.
    The data can only be read by someone who holds the corresponding secret.
  </p>

  <h2>What is Nearbytes?</h2>
  <p>
    Nearbytes is an end-to-end encrypted file and messaging system built on a
    cryptographic event log.  Every change — adding a file, editing a message —
    is recorded as a signed, encrypted event.  Events are content-addressed by
    hash and stored in the <code>channels/</code> tree below.  Encrypted
    content blocks are stored in <code>blocks/</code>.
  </p>

  <h2>Folder layout</h2>
  <pre><code>&lt;root&gt;/
  Nearbytes.html              ← this file (discovery marker, not durable data)
  blocks/
    &lt;sha256-hex&gt;.bin         ← encrypted content blocks
  channels/
    &lt;public-key-hex&gt;/        ← one directory per volume
      &lt;event-hash&gt;.bin       ← signed, encrypted events</code></pre>

  <p>
    File names are lowercase 64-character SHA-256 hex digests.
    The channel directory name is the lowercase hex-encoded uncompressed
    P-256 public key derived from your secret.
  </p>

  <h2>Can I read my files?</h2>
  <p class="note">
    A self-contained reader application will be embedded in this file in a
    future version of Nearbytes.  When it arrives, you will be able to open
    this page in any browser, enter your secret, and access your files —
    no installation required.
  </p>
  <p>
    For now, use the Nearbytes application or the <code>nbf</code> CLI with
    your secret to read and write files.
  </p>

  <h2>Specifications</h2>
  <p>
    The on-disk format is defined by the open Nearbytes protocol specifications
    (<code>storage/meta-storage-v2.md</code>,
    <code>storage/data-correctness-v1.md</code>).
  </p>

  <footer>
    Generated by nearbytes-skeleton.
    This file is rewritten on startup and is not durable storage data.
  </footer>

</body>
</html>
`;
}

/**
 * Reap stale `*.tmp` scratch files inside `dir`.
 *
 * `nearbytes-log/src/internal/fsIo.ts` publishes content-addressed blocks
 * and events via "write to `<final>.<rand>.tmp` → `link` → `unlink` tmp".
 * If a process is killed between the write and the unlink, the tmp file
 * is orphaned. They are harmless (any reader looks up the canonical
 * `<hash>.bin`, never `<hash>.<rand>.tmp`) but they accumulate.
 *
 * This reaper deletes anything matching `*.tmp` in `dir` that is older
 * than the safety window. A safety window matters because another
 * process may be mid-write right now and we MUST NOT yank its tmp out
 * from under it; the `link` step happens within milliseconds of the
 * write, so anything older than a few minutes was definitely orphaned.
 */
const TMP_REAP_AGE_MS = 5 * 60 * 1000; // 5 minutes

async function reapStaleTmpFiles(dir: string): Promise<void> {
  let entries: import('node:fs').Dirent[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return;
    throw err;
  }
  const now = Date.now();
  await Promise.all(
    entries.map(async (entry) => {
      if (!entry.isFile() || !entry.name.endsWith('.tmp')) return;
      const path = join(dir, entry.name);
      try {
        const stats = await stat(path);
        if (now - stats.mtimeMs < TMP_REAP_AGE_MS) return;
        await unlink(path).catch(() => undefined);
      } catch {
        // best-effort: missing/permission errors are not failures here
      }
    }),
  );
}

async function reapStaleTmpFilesRecursive(dir: string): Promise<void> {
  let entries: import('node:fs').Dirent[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return;
    throw err;
  }
  await reapStaleTmpFiles(dir);
  await Promise.all(
    entries.map((entry) =>
      entry.isDirectory() ? reapStaleTmpFilesRecursive(join(dir, entry.name)) : Promise.resolve(),
    ),
  );
}

/**
 * Ensures the storage root at `dataDir` conforms to the Nearbytes
 * meta-storage specification (§4.1):
 *
 *  - Creates `blocks/` and `channels/` directories if missing.
 *  - Writes `Nearbytes.html` (always, to keep it current with this version).
 *  - Deletes `Nearbytes.json` if present (obsolete format; spec §4.1 rule 7).
 *  - Reaps stale `*.tmp` scratch files left by crashed writers (older than
 *    {@link TMP_REAP_AGE_MS}), under `blocks/` and `channels/<pk>/`.
 *
 * Idempotent and safe to call on every startup or after a conflict repair.
 *
 * @param dataDir - Absolute path to the storage root directory.
 */
export async function initializeStorageRoot(dataDir: string): Promise<void> {
  await mkdir(join(dataDir, 'blocks'), { recursive: true });
  await mkdir(join(dataDir, 'channels'), { recursive: true });
  await writeFile(join(dataDir, 'Nearbytes.html'), buildNearbytesHtml(), 'utf8');

  try {
    await access(join(dataDir, 'Nearbytes.json'), constants.F_OK);
    await rm(join(dataDir, 'Nearbytes.json'));
  } catch {}

  await reapStaleTmpFiles(join(dataDir, 'blocks'));
  await reapStaleTmpFilesRecursive(join(dataDir, 'channels'));
}
